version: '3.2'
services:
  postgres.wallet.service:
    container_name: postgres.wallet.service
    hostname: postgres.wallet.service
    image: postgres:15
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    volumes:
      - wallet_service_postgres:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    networks:
      pc-environment-network:
        aliases:
          - postgres.wallet.service
networks:
  pc-environment-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
volumes:
  wallet_service_postgres:
    driver: "local"
