spring:
  application:
    name: ms-wallet
  datasource:
    url: ${MS_WALLET_POSTGRES_DB_URI}
    username: ${MS_WALLET_POSTGRES_DB_USER}
    password: ${MS_WALLET_POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${MS_JWT_SECRET}

  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG