spring:
  application:
    name: ms-wallet
  data:
    mongodb:
      uri: ${MS_WALLET_DB_URI}

api:
  security:
    token:
      secret: ${MS_JWT_SECRET}

  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG